name: heck
description: Helpful Emulator Construction Kit
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  built_collection: ^5.1.1
  built_value: ^8.1.4
#   path: ^1.8.0

dev_dependencies:
  build_runner:
  built_value_generator:
  lints: ^1.0.0
  test: ^1.16.0
